channels:
    - defaults
    - anaconda
    - conda-forge

dependencies:
    - conda-forge::python=3.7.8
    - pillow=6.1
    - pytorch=1.3.1
    - torchvision=0.4.2
    - scikit-image=0.16.2
    - tensorboard
    - tqdm
    - scikit-learn
